version: '3.7'
services:
  db:
    image: postgres
    env_file: ./server/.env
    ports:
      - '5432:5432'
    networks:
      - view
  view-server:
    build: server
    ports:
      - '3001:3001'
    command: npm start
    networks:
      - view
    depends_on:
      - db
    volumes:
      - ./server:/home/node/server/
      - /home/node/server/node_modules
  view-client:
    build: client
    command: npm start
    stdin_open: true
    ports:
      - '3000:3000'
    depends_on:
      - view-server
    volumes:
      - ./client:/home/node/client
      - /home/node/client/node_modules
    networks:
      - view
networks:
  view:
    driver: bridge
